<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 추가 -->
<!DOCTYPE memberList 
[
<!ELEMENT memberList (memberInfo+)>
<!ELEMENT memberInfo (name, telephone, curriculumn, zipCode, addr)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT telephone (#PCDATA)>
<!ELEMENT curriculumn (sub+)>
<!ELEMENT sub (#PCDATA)>
<!ELEMENT zipCode (#PCDATA)>
<!ELEMENT addr (#PCDATA)>
<!ATTLIST memberInfo mid CDATA #IMPLIED>
]>
<!-- 반드시 있어야 되는 속성이면 #REQUIRED
     있기도 하고 없기도 하다라면 #IMPLIED -->
     
<!-- #REQUIRED : 이 속성은 반드시 명시되어야 한다. -->
<!-- #IMPLIED : 이 속성은 명시되기도 하고, 명시되지 않기도 한다. -->
<!-- #FIXED 특정값  : 이 속성은 특정값으로 고정되어 사용된다. -->

<!-- ex) 노은하는 curriculumn이 있는데 김민지는 curriculumn이 없으면?
         그럴때는 <!ELEMENT memberInfo (name, telephone, curriculumn?, zipCode, addr)>
         curriculumn? 를 사용한다. -->

<memberList>
	<memberInfo mid="1">
		<name>노은하</name>
		<telephone><![CDATA[010-1234-4567]]></telephone>
		<curriculumn>
			<sub>JAVA SE</sub>
			<sub>ORACLE</sub>
			<sub><![CDATA[Servlet&JSP]]></sub>
		</curriculumn>
		<zipCode>01234</zipCode>
		<addr>서울시 마포구 월드컵북로 150</addr>
	</memberInfo>
	
	<memberInfo mid="2">
		<name>김민지</name>
		<telephone><![CDATA[010-9987-8876]]></telephone>
		<curriculumn>
			<sub>HTML</sub>
			<sub>CSS</sub>
			<sub>Javascript</sub>
		</curriculumn>
		<zipCode>01285</zipCode>
		<addr>서울시 은평구 통일로 20</addr>
	</memberInfo>
</memberList>